var CONFIGURATION = {
    español: {
        module_information_name: "Información",
        module_services_name: "Servicios",
        module_store_name: "Tienda",
        module_weather_name: "Clima",
        module_account_name: "Cuenta",
        submodule_events_name: "Eventos",
        submodule_places_name: "Lugares de Interés",
        submodule_facilities_name: "Instalaciones",
        submodule_booking_history_name: "Mis reservas",
        submodule_account_state_name: "Estado de Cuenta",
        submodule_language_header: 'Idioma',
        submodule_language_spanish: "Español",
        submodule_language_english: "Inglés",
        submodule_language_portuguese: "Portugués",
        submodule_currency_header: "Moneda",
        submodule_currency_soles: "Soles",
        submodule_currency_dollar: "Dólares",
        submodule_currency_euro: "Euros",
        module_services_first_menu_item: "Gimnasio",
        module_services_second_menu_item: "Spa",
        module_services_third_menu_item: "Restaurante",
        module_account_header_name: "RESUMEN DE CUENTA",
        module_account_subheader_name: "Historial de transacciones",
        module_account_period_name: "Periodo:",
        module_account_amount_name: "Importe:",
        module_account_table_date_name: "Fecha",
        module_account_table_time_name: "Hora",
        module_account_table_description_name: "Descripción",
        module_account_table_amount_name: "Monto",
        module_store_header_name: "Tienda",
        module_booking_history_header_name: "Historial de Reservas",
        submodule_restaurants_header_name: "RESTAURANTE",
        submodule_booking_header_name: "RESERVA",
    },

    ingles: {
        module_information_name: "Information",
        module_services_name: "Services",
        module_store_name: "Store",
        module_weather_name: "Weather",
        module_account_name: "Account",
        submodule_events_name: "Events",
        submodule_places_name: "Places of Interest",
        submodule_facilities_name: "Facilities",
        submodule_booking_history_name: "My reservations",
        submodule_account_state_name: "Account status",
        submodule_language_header: 'Language',
        submodule_language_spanish: "Spanish",
        submodule_language_english: "English",
        submodule_language_portuguese: "Portuguese",
        submodule_currency_header: "Currency",
        submodule_currency_soles: "Soles",
        submodule_currency_dollar: "Dollars",
        submodule_currency_euro: "Euros",
        module_services_first_menu_item: "Gym",
        module_services_second_menu_item: "Spa",
        module_services_third_menu_item: "Restaurant",
        module_account_header_name: "ACCOUNT SUMMARY",
        module_account_subheader_name: "Transaction history",
        module_account_period_name: "Period:",
        module_account_amount_name: "Amount:",
        module_account_table_date_name: "Date",
        module_account_table_time_name: "Hour",
        module_account_table_description_name: "Description",
        module_account_table_amount_name: "Amount",
        module_store_header_name: "Store",
        module_booking_history_header_name: "Booking History",
        submodule_restaurants_header_name: "RESTAURANTS",
        submodule_booking_header_name: "RESERVATION",
        
    },

    portugues: {
        module_information_name: "em formação",
        module_services_name: "Serviços",
        module_store_name: "Loja",
        module_weather_name: "Clima",
        module_account_name: "Conta",
        submodule_events_name: "Eventos",
        submodule_places_name: "Locais de interesse",
        submodule_facilities_name: "Instalações",
        submodule_booking_history_name: "Minhas reservas",
        submodule_account_state_name: "Estado de conta",
        submodule_language_header: 'Língua',
        submodule_language_spanish: "Espanhol",
        submodule_language_english: "Inglês",
        submodule_language_portuguese: "Português",
        submodule_currency_header: "Moeda",
        submodule_currency_soles: "Suns",
        submodule_currency_dollar: "Dólares",
        submodule_currency_euro: "Euros",
        module_services_first_menu_item: "Academia",
        module_services_second_menu_item: "Spa",
        module_services_third_menu_item: "Restaurante",
        module_account_header_name: "RESUMO DA CONTA",
        module_account_period_name: "Período:",
        module_account_amount_name: "Montante:",
        module_account_table_date_name: "Encontro",
        module_account_table_time_name: "Tempo",
        module_account_table_description_name: "Descrição",
        module_account_table_amount_name: "Montante",
        module_store_header_name: "Loja",
        module_booking_history_header_name: "Histórico de reserva",
        module_account_subheader_name: "Histórico de transações",
        submodule_restaurants_header_name: "RESTAURANTE",
        submodule_booking_header_name: "RESERVA",
    },
};
